### PR TITLE
Add .clang-format rules

### PR DESCRIPTION
**Pull request by OnlineCop**
Adds formatting rules for clang-format.
- This is being added separately to actually formatting the source
files, to allow changes to this file before changing everything.

### CODE REVIEW

**Comment by OnlineCop** [comment]
I'd like some feedback on this `.clang-format` style. It replaces tabs with (4) spaces (and indents everything that isn't already 4 spaces). It forces '{' on the next line instead of cuddled on the same one, with exception of initialization lists, so `int foo[] = { ... };` can have the opening '{' on the same line.

In a future commit, `clang-format -i src/*.cpp include/*.h` will be run and reformat all the files. Since that's going to be a very hefty update to all the code, I'm hoping to minimize its impact with this commit.

It is expecting clang-format version 10, with options detailed https://releases.llvm.org/10.0.0/tools/clang/docs/ClangFormatStyleOptions.html. On Ubuntu, `apt-get install clang-format-10` should install the correct version.

Once all nuances of how we want it formatted are hammered out, I'll merge this with **master**, and in the subsequent commit, I'll add all the formatted sources. On occasion, I've seen errors where the order of #include files is modified by this, so minor fix-ups may be required to get it to compile.

**Comment by z9484** [comment]
I like braces on the next line as well so it looks good to me. Gotta get rid of those evil tabs.

I've been working on replacing the graphics. I've made good progress on newtown, Though the entities are going to take a while. Being forced to use kq's palette slows things down, but the one plus side is it does help it look more consistent. 
I have been collecting music from opengameart but I don't think DUMB supports mp3/ogg so that is going to be more work.

**Comment by OnlineCop** [comment]
@z9484: Were you able to run `clang-format` with these settings and look through the code? If you have no issues with how it looks, I'll merge it in. If there are any "well, I could live with this *but* my personal preference is to..." then don't feel afraid of voicing them. I'd rather have the main (read: still interested in this project) contributors working with formatting they love, instead of just one they can tolerate.

Are your changes to the graphics/palette code-based? If so, and we reformat all the files, it may show up as a large list of conflicts on your end. To help ease that pain, we could just have *you* perform the `clang-format -i ...` on the code. That could mean less work on your end.

Of course, if you're simply swapping graphics, then that would be moot.

**Comment by z9484** [comment]
I took a look at the code and it seemed fine to me but you were right and it looks like it messed up an include in disk.h so its not compiling right now. 
The graphic changes so far have been only with the images so they won't be affected.

**Pull request merged**
