### PR TITLE
Fix linux

### PR DESCRIPTION
**Pull request by z9484**
If you would like these changes I would recommend creating a new develop branch so I am not pushing to master.

### CODE REVIEW

**Comment by OnlineCop** [comment]
You're able to compile and run this on Linux?

Since I can't get it working on Win10 or OS X, I might try Linux in a VM.

Most of my development has been halted due to being unable to get it to render (it compiles, but I need to actually see results).

**Comment by z9484** [comment]
Hmm strange, I got it to compile in an old linux mint vm and with Visualstudio community 2015 and then also 2019. Full screen mode seems to be broken still, do you have it enabled?

**Comment by OnlineCop** [comment]
I don't think I've ever enabled fullscreen mode; it's always been windowed for me.

I'm installing Ubuntu 20 in VirtualBox now. I'd like to actually see if I can get it to run.

My conversion from C to C++ had a bunch of hidden gotchas, like when it would `strcpy` the same `std::string` more than once: a "double delete" crash would occur in some obscure location when the 2nd string went out of scope.

**Comment by z9484** [comment]
Yeah the fact that a shared_ptr to a string was causing a memory error was really perplexing so I switched it so player2fighter just uses the move constructor instead of memcopy

**Comment by OnlineCop** [comment]
It looks like quite a few of the headers and libs are under `deps/` but the CMake isn't finding them. What could we do to have it search there first before the ones found on the system?

**Comment by z9484** [comment]
On linux? The deps/lib are all windows binaries so I just did the apt-get packages that I added to the readme. I just tried it on a fresh ubuntu mate 20.04 and then I got that old bug again where the cursor moves on its own as if the top and left buttons are permanently pressed. It worked fine on my old mint vm... If I remember it might be a bug with allegro, but its been too long to remember if we ever found a remedy for it.

**Comment by OnlineCop** [comment]
Looks good to me. I see the same "pull up-left" that you are; I suspect something I did in a previous refactor contributed to that.

**Comment by OnlineCop** [comment]
I edited `~/.kq/kq.cfg` and changed `use_joy = 1` to `use_joy = 0` and the "up-and-left" seems to go away. So somewhere in all this, the logic for using a joystick is interfering with the keyboard controls.

**Comment by OnlineCop** [comment]
Is there a way to simplify CMakeFiles.txt in the way it looks for Lua,
Dumb, Allegro, etc.?

I don’t know how many people have, or will, play with a joystick. Should we
maintain it, or remove code and support for it?

**Comment by z9484** [comment]
I wouldn't go that far as as on windows an xbox controller was being registered as the joystick and it seemed to be working. But I got nothing at all in the ubuntu vm.

I'm not following you on cmake. Findlua, findDumb were working for me on linux. They alerted me to the libraries I needed to install and when I installed them, it found them. I haven't generated a visual studio project with cmake on windows because there was already a sln checked in to version control.

**Pull request merged**
